# Generated by Django 4.2.2 on 2023-06-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0005_studentclassinfo_class_short_form"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
